<a href="https://colab.research.google.com/github/SAHAJCHAUDHARY45/Python/blob/main/DL_LAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_iris
iris=load_iris()
x1=iris.data
y1=iris.target
feature_name=iris.feature_names
target_name=iris.target_names
print(feature_name)
print(target_name)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


In [ ]:
from sklearn.model_selection import train_test_split
x1_train,x1_test,y1_train,y1_test=train_test_split(x1,y1,test_size=0.3,random_state=1)
y1_train = y1_train.reshape(-1, 1)
y1_test = y1_test.reshape(-1, 1)
print(x1_train.shape)
print(x1_test.shape)
print(y1_train.shape)
print(y1_test.shape)

(105, 4)
(45, 4)
(105, 1)
(45, 1)


In [ ]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

input_neurons=x1_train.shape[1]
hidden_neurons=8
output_neurons=y1_train.shape[1]
learning_rate=0.01
w_input_hidden=np.random.rand(input_neurons,hidden_neurons)
b_hidden=np.random.rand(1,hidden_neurons)
w_hidden_output=np.random.rand(hidden_neurons,output_neurons)
b_output=np.random.rand(1,output_neurons)
epochs=100
for epoch in range(epochs):
    hidden_input=np.dot(x1_train,w_input_hidden)+b_hidden
    hidden_output=sigmoid(hidden_input)
    final_input=np.dot(hidden_output,w_hidden_output)+b_output
    final_output=sigmoid(final_input)
    error=(y1_train-final_output)
    print(error)


Streaming output truncated to the last 5000 lines.
 [ 0.01699674]
 [ 1.0169884 ]
 [ 1.01699374]
 [-0.9827769 ]
 [-0.98278814]
 [ 0.01702559]
 [-0.98267255]
 [ 1.01697616]
 [ 0.01700513]
 [ 1.01697316]
 [ 1.01698321]
 [ 0.01701233]
 [ 1.01698306]
 [ 1.01697381]
 [ 0.01703877]
 [-0.98290006]
 [ 0.01702932]
 [-0.98236267]
 [ 0.01705495]
 [ 0.01698536]
 [-0.98276617]
 [ 0.01699029]
 [-0.98278798]
 [-0.98276969]
 [ 1.01698083]
 [ 1.01700266]
 [ 1.01697753]
 [-0.98270785]
 [-0.9827956 ]
 [ 0.01699536]
 [-0.98262413]
 [ 1.01699821]
 [-0.98268302]
 [ 1.01698559]
 [ 1.01703926]
 [-0.98261845]
 [ 1.01698347]
 [-0.98239859]
 [ 0.01702092]
 [-0.98251342]
 [ 0.01706128]
 [ 0.01712582]
 [-0.98274846]
 [-0.98264422]
 [ 0.01712122]
 [-0.98259224]
 [ 0.01700982]
 [ 0.01699949]
 [-0.98273788]
 [ 0.01698911]
 [ 0.01701796]
 [ 0.01701265]
 [ 0.01698575]
 [ 1.01699821]
 [-0.98281628]
 [-0.98270178]
 [ 1.01699129]
 [ 0.01701533]
 [ 1.01697796]
 [ 0.01705371]
 [ 1.01699213]
 [ 1.01698386]
 [ 0.0169984 ]
 [ 1

In [ ]:
def sigmoid_derivative(x):
    return (x*(1-x))


for epoch in range(epochs):
    hidden_input=np.dot(x1_train,w_input_hidden)+b_hidden
    hidden_output=sigmoid(hidden_input)
    final_input=np.dot(hidden_output,w_hidden_output)+b_output
    final_output=sigmoid(final_input)
    error=(y1_train-final_output)

    #backward pass
    output_delta=error*sigmoid_derivative(final_output)
    hidden_error=output_delta.dot(w_hidden_output.T)
    hidden_delta=error*sigmoid_derivative(hidden_output)
    w_hidden_output+=learning_rate*hidden_output.T.dot(output_delta)
    b_output+=learning_rate*np.sum(output_delta,axis=0,keepdims=True)
    w_input_hidden+=learning_rate*x1_train.T.dot(hidden_delta)
    b_hidden+=learning_rate*np.sum(hidden_delta,axis=0,keepdims=True)

if(epoch%100==0):
    loss=np.mean(np.square(error))
    print(f'Epochs: {epoch}, Loss:{loss}')

hidden_input=np.dot(x1_test,w_input_hidden)+b_hidden
hidden_output=sigmoid(hidden_input)
final_input=np.dot(hidden_output,w_hidden_output)+b_output
final_output=sigmoid(final_input)

prediction=np.argmax(final_output,axis=1)
y_actual=np.argmax(y1_test,axis=1)

accuracy=np.mean(prediction==y_actual)
print(accuracy)

1.0


In [ ]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

input_neurons = x1_train.shape[1]  # Number of input features
hidden_neurons = 8
output_neurons = y1_train.shape[1]  # Assuming one-hot encoded output
learning_rate = 0.01

# Initialize weights and biases
w_input_hidden = np.random.rand(input_neurons, hidden_neurons)
b_hidden = np.random.rand(1, hidden_neurons)
w_hidden_output = np.random.rand(hidden_neurons, output_neurons)
b_output = np.random.rand(1, output_neurons)

epochs = 1000  # Increase epochs for better learning

# Training loop
for epoch in range(epochs):
    # Forward pass
    hidden_input = np.dot(x1_train, w_input_hidden) + b_hidden
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, w_hidden_output) + b_output
    final_output = sigmoid(final_input)

    # Compute error
    error = y1_train - final_output

    # Backpropagation
    output_delta = error * sigmoid_derivative(final_output)
    hidden_error = output_delta.dot(w_hidden_output.T)
    hidden_delta = hidden_error * sigmoid_derivative(hidden_output)  # Fixed this line

    # Update weights and biases
    w_hidden_output += learning_rate * hidden_output.T.dot(output_delta)
    b_output += learning_rate * np.sum(output_delta, axis=0, keepdims=True)
    w_input_hidden += learning_rate * x1_train.T.dot(hidden_delta)
    b_hidden += learning_rate * np.sum(hidden_delta, axis=0, keepdims=True)

    # Print loss every 100 epochs
    if epoch % 100 == 0:
        loss = np.mean(np.square(error))
        print(f'Epoch: {epoch}, Loss: {loss}')

# Testing
hidden_input = np.dot(x1_test, w_input_hidden) + b_hidden
hidden_output = sigmoid(hidden_input)
final_input = np.dot(hidden_output, w_hidden_output) + b_output
final_output = sigmoid(final_input)

# Convert predictions to class labels
prediction = np.argmax(final_output, axis=1)
y_actual = np.argmax(y1_test, axis=1)  # Ensure y1_test is one-hot encoded

# Fix shape mismatch for accuracy calculation
if prediction.shape != y_actual.shape:
    print(f"Shape mismatch: prediction {prediction.shape}, y_actual {y_actual.shape}")
else:
    accuracy = np.mean(prediction == y_actual)
    print(f'Accuracy: {accuracy}')


Epoch: 0, Loss: 0.6951965350429248
Epoch: 100, Loss: 0.6950514274464316
Epoch: 200, Loss: 0.6945834522856994
Epoch: 300, Loss: 0.6861103866596516
Epoch: 400, Loss: 0.43781467253401146
Epoch: 500, Loss: 0.3855316356929543
Epoch: 600, Loss: 0.3722614229365033
Epoch: 700, Loss: 0.3664506288862385
Epoch: 800, Loss: 0.36322685254140163
Epoch: 900, Loss: 0.36118727145264057
Accuracy: 1.0


In [ ]:

import pandas as pd

df = pd.read_csv("/content/sample_data/dataset.csv")

df.info(), df.head()



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Glucose        768 non-null    int64  
 1   BloodPressure  768 non-null    int64  
 2   SkinThickness  768 non-null    int64  
 3   Insulin        768 non-null    int64  
 4   BMI            768 non-null    float64
 5   Age            768 non-null    int64  
 6   Outcome        768 non-null    int64  
dtypes: float64(1), int64(6)
memory usage: 42.1 KB


(None,
    Glucose  BloodPressure  SkinThickness  Insulin   BMI  Age  Outcome
 0      148             72             35        0  33.6   50        1
 1       85             66             29        0  26.6   31        0
 2      183             64              0        0  23.3   32        1
 3       89             66             23       94  28.1   21        0
 4      137             40             35      168  43.1   33        1)

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = df.drop(columns=['Outcome']).values  # Features
y = df['Outcome'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

y_train_onehot = np.eye(2)[y_train]
y_test_onehot = np.eye(2)[y_test]

input_neurons = X_train.shape[1]
hidden_neurons = 8
output_neurons = 2
learning_rate = 0.01
epochs = 1000

np.random.seed(42)
w_input_hidden = np.random.rand(input_neurons, hidden_neurons)
b_hidden = np.random.rand(1, hidden_neurons)
w_hidden_output = np.random.rand(hidden_neurons, output_neurons)
b_output = np.random.rand(1, output_neurons)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

for epoch in range(epochs):
    hidden_input = np.dot(X_train, w_input_hidden) + b_hidden
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, w_hidden_output) + b_output
    final_output = sigmoid(final_input)

    error = y_train_onehot - final_output

    output_delta = error * sigmoid_derivative(final_output)
    hidden_error = output_delta.dot(w_hidden_output.T)
    hidden_delta = hidden_error * sigmoid_derivative(hidden_output)

    w_hidden_output += learning_rate * hidden_output.T.dot(output_delta)
    b_output += learning_rate * np.sum(output_delta, axis=0, keepdims=True)
    w_input_hidden += learning_rate * X_train.T.dot(hidden_delta)
    b_hidden += learning_rate * np.sum(hidden_delta, axis=0, keepdims=True)

    if epoch % 100 == 0:
        loss = np.mean(np.square(error))
        print(f'Epoch: {epoch}, Loss: {loss}')

hidden_input = np.dot(X_test, w_input_hidden) + b_hidden
hidden_output = sigmoid(hidden_input)
final_input = np.dot(hidden_output, w_hidden_output) + b_output
final_output = sigmoid(final_input)

prediction = np.argmax(final_output, axis=1)
y_actual = np.argmax(y_test_onehot, axis=1)

accuracy = np.mean(prediction == y_actual)
print(f'Accuracy: {accuracy:.4f}')

Epoch: 0, Loss: 0.43724866798186174
Epoch: 100, Loss: 0.15165592665464694
Epoch: 200, Loss: 0.14573626908654128
Epoch: 300, Loss: 0.14407926796211806
Epoch: 400, Loss: 0.14267006678296457
Epoch: 500, Loss: 0.14124150727504606
Epoch: 600, Loss: 0.1400984871793519
Epoch: 700, Loss: 0.13912927434486044
Epoch: 800, Loss: 0.13814666455401123
Epoch: 900, Loss: 0.1369290092041092
Accuracy: 0.7273


In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
iris = load_iris()
x = iris.data
y = iris.target
feature_names = iris.feature_names
target_names = iris.target_names
print("x:",x)
print("y:",y)
print("Feature:",feature_names)
print("target:",target_names)
print("x_train shape:",x.shape)
print("y_train shape:",y.shape)

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)
print("x_Test shape:",x_test.shape)
print("y_Test shape:",y_test.shape)

x: [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1

In [ ]:
import keras
from keras.datasets import mnist
from keras.layers import Dense, Activation, Flatten, MaxPooling2D , Conv2D
from keras.models import Sequential
from keras.utils import to_categorical
import numpy as np
import matplotlib.pyplot as plt


(train_x,train_y),(test_x,test_y) = mnist.load_data()
train_x = train_x.reshape(-1,28,28,1)
test_x = test_x.reshape(-1,28,28,1)
print(train_x.shape)
print(test_x.shape)

train_x = train_x.astype('float32')
test_x = test_x.astype('float32')
train_x /=255
test_x/=255

model = Sequential() # Use with Uppercase S
model.add(Conv2D(64,(3,3),input_shape=(28,28,1))) # Change conv2D to Conv2D
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model = Sequential()
model.add(Conv2D(64,(3,3),input_shape=(28,28,1))) # Change conv2D to Conv2D
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

(60000, 28, 28, 1)
(10000, 28, 28, 1)


/usr/local/lib/python3.11/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
